# ===========================
# PostgreSQL Database
# ===========================
spring.datasource.url=jdbc:postgresql://dpg-d96egjkvikkc73boomp0-a:5432/helpdesk_89vf
spring.datasource.username=helpdeskuser
spring.datasource.password=kDWP9SUAKyC8JGdklQdQsUOPy6h4PLx9

spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===========================
# Server
# ===========================
server.port=${PORT:8080}

# ===========================
# Email
# ===========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=temp@gmail.com
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true